In [17]:
import pandas as pd

In [18]:
import numpy as np

In [19]:
orders = pd.read_csv(r"C:\Users\Huawei\Desktop\data science\project resume\zepto\archive\blinkit_orders.csv")

In [20]:
order_items = pd.read_csv(r"C:\Users\Huawei\Desktop\data science\project resume\zepto\archive\blinkit_order_items.csv")

In [21]:
products = pd.read_csv(r"C:\Users\Huawei\Desktop\data science\project resume\zepto\archive\blinkit_products.csv")

In [22]:
customers = pd.read_csv(r"C:\Users\Huawei\Desktop\data science\project resume\zepto\archive\blinkit_customers.csv")

In [23]:
orders.head()

,order_id,customer_id,order_date,promised_delivery_time,actual_delivery_time,delivery_status,order_total,payment_method,delivery_partner_id,store_id
0,1961864118,30065862,2024-07-17 08:34:01,2024-07-17 08:52:01,2024-07-17 08:47:01,On Time,3197.07,Cash,63230,4771
1,1549769649,9573071,2024-05-28 13:14:29,2024-05-28 13:25:29,2024-05-28 13:27:29,On Time,976.55,Cash,14983,7534
2,9185164487,45477575,2024-09-23 13:07:12,2024-09-23 13:25:12,2024-09-23 13:29:12,On Time,839.05,UPI,39859,9886
3,9644738826,88067569,2023-11-24 16:16:56,2023-11-24 16:34:56,2023-11-24 16:33:56,On Time,440.23,Card,61497,7917
4,5427684290,83298567,2023-11-20 05:00:39,2023-11-20 05:17:39,2023-11-20 05:18:39,On Time,2526.68,Cash,84315,2741

In [24]:
import os
os.listdir()

['.ipynb_checkpoints',
 'blinkit.ipynb',
 'blinkit_customers.csv',
 'blinkit_customer_feedback.csv',
 'blinkit_delivery_performance.csv',
 'blinkit_inventory.csv',
 'blinkit_inventoryNew.csv',
 'blinkit_marketing_performance.csv',
 'blinkit_orders.csv',
 'blinkit_order_items.csv',
 'blinkit_products.csv',
 'Category_Icons.xlsx',
 'Rating_Icon.xlsx']

In [25]:
order_items.head()

     order_id  product_id  quantity  unit_price
0  1961864118      642612         3      517.03
1  1549769649      378676         1      881.42
2  9185164487      741341         2      923.84
3  9644738826      561860         1      874.78
4  5427684290      602241         2      976.55

In [26]:
orders.columns
order_items.columns
products.columns
customers.columns

Index(['customer_id', 'customer_name', 'email', 'phone', 'address', 'area',
       'pincode', 'registration_date', 'customer_segment', 'total_orders',
       'avg_order_value'],
      dtype='object')

In [27]:
df = pd.merge(order_items, orders, on="order_id")

In [28]:
df.head()

,order_id,product_id,quantity,unit_price,customer_id,order_date,promised_delivery_time,actual_delivery_time,delivery_status,order_total,payment_method,delivery_partner_id,store_id
0,1961864118,642612,3,517.03,30065862,2024-07-17 08:34:01,2024-07-17 08:52:01,2024-07-17 08:47:01,On Time,3197.07,Cash,63230,4771
1,1549769649,378676,1,881.42,9573071,2024-05-28 13:14:29,2024-05-28 13:25:29,2024-05-28 13:27:29,On Time,976.55,Cash,14983,7534
2,9185164487,741341,2,923.84,45477575,2024-09-23 13:07:12,2024-09-23 13:25:12,2024-09-23 13:29:12,On Time,839.05,UPI,39859,9886
3,9644738826,561860,1,874.78,88067569,2023-11-24 16:16:56,2023-11-24 16:34:56,2023-11-24 16:33:56,On Time,440.23,Card,61497,7917
4,5427684290,602241,2,976.55,83298567,2023-11-20 05:00:39,2023-11-20 05:17:39,2023-11-20 05:18:39,On Time,2526.68,Cash,84315,2741

In [29]:
df = pd.merge(df, products, on="product_id")

In [30]:
df.head()

,order_id,product_id,quantity,unit_price,customer_id,order_date,promised_delivery_time,actual_delivery_time,delivery_status,order_total,...,store_id,product_name,category,brand,price,mrp,margin_percentage,shelf_life_days,min_stock_level,max_stock_level
0,1961864118,642612,3,517.03,30065862,2024-07-17 08:34:01,2024-07-17 08:52:01,2024-07-17 08:47:01,On Time,3197.07,...,4771,Pet Treats,Pet Care,Pillay-Ahuja,517.03,795.43,35.0,365,16,57
1,1549769649,378676,1,881.42,9573071,2024-05-28 13:14:29,2024-05-28 13:25:29,2024-05-28 13:27:29,On Time,976.55,...,7534,Orange Juice,Cold Drinks & Juices,Baral-Kamdar,881.42,1259.17,30.0,180,19,65
2,9185164487,741341,2,923.84,45477575,2024-09-23 13:07:12,2024-09-23 13:25:12,2024-09-23 13:29:12,On Time,839.05,...,9886,Eggs,Dairy & Breakfast,Prasad LLC,923.84,1154.80,20.0,7,13,62
3,9644738826,561860,1,874.78,88067569,2023-11-24 16:16:56,2023-11-24 16:34:56,2023-11-24 16:33:56,On Time,440.23,...,7917,Orange Juice,Cold Drinks & Juices,Gupta Ltd,874.78,1249.69,30.0,180,21,90
4,5427684290,602241,2,976.55,83298567,2023-11-20 05:00:39,2023-11-20 05:17:39,2023-11-20 05:18:39,On Time,2526.68,...,2741,Nuts,Snacks & Munchies,Bahl-Pau,976.55,1502.38,35.0,90,12,75

In [31]:
df = pd.merge(df, customers, on="customer_id")

In [32]:
df.head()

,order_id,product_id,quantity,unit_price,customer_id,order_date,promised_delivery_time,actual_delivery_time,delivery_status,order_total,...,customer_name,email,phone,address,area,pincode,registration_date,customer_segment,total_orders,avg_order_value
0,1961864118,642612,3,517.03,30065862,2024-07-17 08:34:01,2024-07-17 08:52:01,2024-07-17 08:47:01,On Time,3197.07,...,Urishilla Hegde,ydeo@example.org,910400446367,"H.No. 330\nRana Path, Sagar 712033",Allahabad,911359,2024-09-02,Regular,13,749.95
1,1549769649,378676,1,881.42,9573071,2024-05-28 13:14:29,2024-05-28 13:25:29,2024-05-28 13:27:29,On Time,976.55,...,Ranveer Mahal,phegde@example.org,912292591574,"49, Sarkar Zila, Navi Mumbai-077374",Thrissur,856100,2023-11-07,New,5,958.06
2,9185164487,741341,2,923.84,45477575,2024-09-23 13:07:12,2024-09-23 13:25:12,2024-09-23 13:29:12,On Time,839.05,...,Aarna Bawa,kondajagdish@example.com,912719661653,"14/351, Agarwal Path\nMedininagar 636193",Vellore,117423,2024-01-05,Inactive,4,327.93
3,9644738826,561860,1,874.78,88067569,2023-11-24 16:16:56,2023-11-24 16:34:56,2023-11-24 16:33:56,On Time,440.23,...,Aayush Sengupta,lekha10@example.com,913367647372,"20/47\nRatta Chowk, Sonipat-022522",Gaya,288459,2023-12-25,Premium,5,273.38
4,5427684290,602241,2,976.55,83298567,2023-11-20 05:00:39,2023-11-20 05:17:39,2023-11-20 05:18:39,On Time,2526.68,...,Vansha Kuruvilla,xalak62@example.com,912910638833,"H.No. 68, Gaba Road\nKhandwa 040880",Asansol,149383,2024-10-02,Premium,14,763.10

In [33]:
df["Total_Sales"] = df["quantity"] * df["price"]

In [34]:
df.head()

,order_id,product_id,quantity,unit_price,customer_id,order_date,promised_delivery_time,actual_delivery_time,delivery_status,order_total,...,email,phone,address,area,pincode,registration_date,customer_segment,total_orders,avg_order_value,Total_Sales
0,1961864118,642612,3,517.03,30065862,2024-07-17 08:34:01,2024-07-17 08:52:01,2024-07-17 08:47:01,On Time,3197.07,...,ydeo@example.org,910400446367,"H.No. 330\nRana Path, Sagar 712033",Allahabad,911359,2024-09-02,Regular,13,749.95,1551.09
1,1549769649,378676,1,881.42,9573071,2024-05-28 13:14:29,2024-05-28 13:25:29,2024-05-28 13:27:29,On Time,976.55,...,phegde@example.org,912292591574,"49, Sarkar Zila, Navi Mumbai-077374",Thrissur,856100,2023-11-07,New,5,958.06,881.42
2,9185164487,741341,2,923.84,45477575,2024-09-23 13:07:12,2024-09-23 13:25:12,2024-09-23 13:29:12,On Time,839.05,...,kondajagdish@example.com,912719661653,"14/351, Agarwal Path\nMedininagar 636193",Vellore,117423,2024-01-05,Inactive,4,327.93,1847.68
3,9644738826,561860,1,874.78,88067569,2023-11-24 16:16:56,2023-11-24 16:34:56,2023-11-24 16:33:56,On Time,440.23,...,lekha10@example.com,913367647372,"20/47\nRatta Chowk, Sonipat-022522",Gaya,288459,2023-12-25,Premium,5,273.38,874.78
4,5427684290,602241,2,976.55,83298567,2023-11-20 05:00:39,2023-11-20 05:17:39,2023-11-20 05:18:39,On Time,2526.68,...,xalak62@example.com,912910638833,"H.No. 68, Gaba Road\nKhandwa 040880",Asansol,149383,2024-10-02,Premium,14,763.10,1953.10

In [35]:
df["Total_Sales"].sum()

np.float64(4972415.43)

In [36]:
df.groupby("product_name")["Total_Sales"].sum().sort_values(ascending=False).head(10)

product_name
Vitamins          260822.01
Pet Treats        252007.37
Cough Syrup       203569.98
Toilet Cleaner    199837.48
Bread             184851.10
Dish Soap         184441.21
Cat Food          166596.39
Baby Wipes        158768.41
Onions            138858.42
Baby Food         137442.79
Name: Total_Sales, dtype: float64

In [39]:
df.groupby("category")["Total_Sales"].sum()

category
Baby Care                348227.18
Cold Drinks & Juices     392717.62
Dairy & Breakfast        639222.19
Fruits & Vegetables      559053.08
Grocery & Staples        359937.82
Household Care           444244.25
Instant & Frozen Food    307212.65
Personal Care            394894.61
Pet Care                 539888.75
Pharmacy                 592368.57
Snacks & Munchies        394648.71
Name: Total_Sales, dtype: float64

In [41]:
df.columns

Index(['order_id', 'product_id', 'quantity', 'unit_price', 'customer_id',
       'order_date', 'promised_delivery_time', 'actual_delivery_time',
       'delivery_status', 'order_total', 'payment_method',
       'delivery_partner_id', 'store_id', 'product_name', 'category', 'brand',
       'price', 'mrp', 'margin_percentage', 'shelf_life_days',
       'min_stock_level', 'max_stock_level', 'customer_name', 'email', 'phone',
       'address', 'area', 'pincode', 'registration_date', 'customer_segment',
       'total_orders', 'avg_order_value', 'Total_Sales'],
      dtype='object')

In [43]:
df.groupby("area")["Total_Sales"].sum()

area
Adoni            19501.09
Agartala         21911.48
Agra             32294.65
Ahmedabad         9029.36
Ahmednagar       30887.71
                   ...
Vijayanagaram     5714.51
Vijayawada       10384.98
Visakhapatnam    13502.05
Warangal         13023.04
Yamunanagar      21940.10
Name: Total_Sales, Length: 316, dtype: float64

In [44]:
df.to_csv("zepto_dashboard_data.csv", index=False)